# pull_request_rules:
#   - name: automatic merge when CI passes and 2 reviews
#     conditions:
#       - "#approved-reviews-by>=2"
#       - status-success=Travis CI - Pull Request
#       - base=master
#     actions:
#       merge:
#         method: merge
#         strict: true

pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge