dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm i typescript@3.2.2 --save-dev --save-exact
  - npm i core-js@2.6.5
  - npm update
  - sudo apt autoremove
  # - ng update
  # - npm i --only=dev
  # - npm uninstall -g @angular/cli
  # - npm cache clean --force
  # - npm install -g @angular/cli@latest
  # - npm install node-sass -g
  # - npm install --save-dev @angular-devkit/build-angular
  # - npm install --save @angular-devkit/build-angular
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - ./node_modules

install:
  - pushd $TRAVIS_BUILD_DIR
  - npm install

script:
  - npm run build

notifications:
  email:
    recipients:
      - walterplatnumz@gmail.com
    on_failure: always
    on_success: always
  slack: hisptz:2UQgrRwNrI14ohefnnPyzms7
