# version: 2
# jobs:
#   build:
#     working_directory: ~/my-project
#     docker:
#       - image: circleci/node:8-browsers
#     steps:
#       - checkout
#       - restore_cache:
#           key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
#       - run: npm install
#       - save_cache:
#           key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
#           paths:
#             - "node_modules"
# - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
# - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8-browsers

#     working_directory: ~/ngstack-core

#     steps:
#       - checkout

#       - restore_cache:
#           key: ngstack-core-{{ .Branch }}-{{ checksum "package.json" }}

#       - run: npm install

#       - save_cache:
#           key: ngstack-core-{{ .Branch }}-{{ checksum "package.json" }}
#           paths:
#             - 'node_modules'

#       # - run: npm run spellcheck
#       - run: xvfb-run -a npm test -- code-editor --watch=false

version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      # - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
